name: Build and test projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-chapter-2-simple-project-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-2/chapter-2-simple-project
      run: ./mvnw -B clean verify

  build-chapter-3-quarkus-rest-json-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-3/chapter-3-quarkus-rest-json
      run: ./mvnw -B clean verify
        
  build-chapter-3-spring-rest-json-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-3/chapter-3-spring-rest-json
      run: ./mvnw -B clean verify

  build-chapter-3-spring-webflux-rest-json-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-3/chapter-3-spring-webflux-rest-json
      run: ./mvnw -B clean verify

  build-chapter-4-quarkus-panache-activerecord-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-quarkus-panache-activerecord
      run: ./mvnw -B clean verify

  build-chapter-4-quarkus-panache-reactive-activerecord-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-quarkus-panache-reactive-activerecord
      run: ./mvnw -B clean verify
      
  build-chapter-4-quarkus-panache-reactive-repository-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-quarkus-panache-reactive-repository
      run: ./mvnw -B clean verify
      
  build-chapter-4-quarkus-panache-repository-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-quarkus-panache-repository
      run: ./mvnw -B clean verify
      
  build-chapter-4-spring-data-jpa-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-spring-data-jpa
      run: ./mvnw -B clean verify
      
  build-chapter-4-spring-data-r2dbc-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-spring-data-r2dbc
      run: ./mvnw -B clean verify
      
  build-chapter-5-quarkus-cloud-events-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-quarkus-cloud-events
      run: ./mvnw -B clean verify
      
  build-chapter-5-quarkus-kafka-streams-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-quarkus-kafka-streams
      run: ./mvnw -B clean verify
      
  build-chapter-5-quarkus-vertx-eventbus-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-quarkus-vertx-eventbus
      run: ./mvnw -B clean verify

  build-chapter-5-spring-cloud-events-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-spring-cloud-events
      run: ./mvnw -B clean verify
      
  build-chapter-5-spring-eventbus-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-spring-eventbus
      run: ./mvnw -B clean verify
      
  build-chapter-5-spring-kafka-streams-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-spring-kafka-streams
      run: ./mvnw -B clean verify
      
  build-chapter-6-quarkus-rest-cloud-config-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest-cloud-config
      run: ./mvnw -B clean verify
      
  build-chapter-6-quarkus-rest-config-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest-config
      run: ./mvnw -B clean verify
      
  build-chapter-6-quarkus-rest-database-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest-database
      run: ./mvnw -B clean verify

  build-chapter-6-quarkus-rest-debug-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest-debug
      run: ./mvnw -B clean verify

  build-chapter-6-quarkus-rest-monitoring-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest-monitoring
      run: ./mvnw -B clean verify
      
  build-chapter-6-quarkus-rest-j11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest
      run: ./mvnw -B clean verify

  build-chapter-2-simple-project-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-2/chapter-2-simple-project
      run: ./mvnw -B clean verify

  build-chapter-3-quarkus-rest-json-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-3/chapter-3-quarkus-rest-json
      run: ./mvnw -B clean verify
        
  build-chapter-3-spring-rest-json-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-3/chapter-3-spring-rest-json
      run: ./mvnw -B clean verify

  build-chapter-3-spring-webflux-rest-json-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-3/chapter-3-spring-webflux-rest-json
      run: ./mvnw -B clean verify

  build-chapter-4-quarkus-panache-activerecord-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-quarkus-panache-activerecord
      run: ./mvnw -B clean verify

  build-chapter-4-quarkus-panache-reactive-activerecord-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-quarkus-panache-reactive-activerecord
      run: ./mvnw -B clean verify
      
  build-chapter-4-quarkus-panache-reactive-repository-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-quarkus-panache-reactive-repository
      run: ./mvnw -B clean verify
      
  build-chapter-4-quarkus-panache-repository-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-quarkus-panache-repository
      run: ./mvnw -B clean verify
      
  build-chapter-4-spring-data-jpa-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-spring-data-jpa
      run: ./mvnw -B clean verify
      
  build-chapter-4-spring-data-r2dbc-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-4/chapter-4-spring-data-r2dbc
      run: ./mvnw -B clean verify
      
  build-chapter-5-quarkus-cloud-events-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-quarkus-cloud-events
      run: ./mvnw -B clean verify
      
  build-chapter-5-quarkus-kafka-streams-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-quarkus-kafka-streams
      run: ./mvnw -B clean verify
      
  build-chapter-5-quarkus-vertx-eventbus-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-quarkus-vertx-eventbus
      run: ./mvnw -B clean verify

  build-chapter-5-spring-cloud-events-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-spring-cloud-events
      run: ./mvnw -B clean verify
      
  build-chapter-5-spring-eventbus-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-spring-eventbus
      run: ./mvnw -B clean verify
      
  build-chapter-5-spring-kafka-streams-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-5/chapter-5-spring-kafka-streams
      run: ./mvnw -B clean verify
      
  build-chapter-6-quarkus-rest-cloud-config-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest-cloud-config
      run: ./mvnw -B clean verify
      
  build-chapter-6-quarkus-rest-config-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest-config
      run: ./mvnw -B clean verify
      
  build-chapter-6-quarkus-rest-database-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest-database
      run: ./mvnw -B clean verify

  build-chapter-6-quarkus-rest-debug-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest-debug
      run: ./mvnw -B clean verify

  build-chapter-6-quarkus-rest-monitoring-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest-monitoring
      run: ./mvnw -B clean verify
      
  build-chapter-6-quarkus-rest-j17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: mvn clean verify
      working-directory: chapter-6/chapter-6-quarkus-rest
      run: ./mvnw -B clean verify